# Generated by Django 2.2.3 on 2019-10-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=50)),
                ('track_deck', models.TextField()),
                ('track_date', models.DateField()),
                ('track_url', models.TextField()),
            ],
            options={
                'ordering': ('-track_date',),
            },
        ),
    ]
