# Generated by Django 2.2.3 on 2019-10-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='short_url',
            field=models.CharField(default='Short url', max_length=50),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_name',
            field=models.CharField(max_length=60),
        ),
    ]
