# Generated by Django 2.2.3 on 2019-10-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20191008_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='buy_url',
            field=models.TextField(default='Buy Url'),
        ),
    ]
